### ISSUE TITLE
Changing license for GPL 2 compatibility

### ISSUE THREAD

**Issue by tardyp** [tavendo/AutobahnJS#125]
Project like buildbot would like to include AutobahnJS as part of their application can't due to GPLv2 policy.
It is even more difficult for JS, as you usually minify vendor scripts with the code of your application to minimize load latency, and distribute the resulting code as a binary package. (This is actually what buildbot www is doing)

Like for Python project, I volunteer to manage the switch.

**Comment by tardyp** [comment]
I did not realize it is already MIT!

**Comment by oberstet** [comment]
Yes, it's MIT .. we did the license switch long long ago when actually the only contributor was me. So no issue here luckily. I hope we get AutobahnPython moved to MIT too. Actually all the Autobahns.

Am 14.02.2015 21:37 schrieb Pierre Tardy <notifications@github.com>:

Project like buildbot would like to include AutobahnJS as part of their application can't due to GPLv2 policy.
It is even more difficult for JS, as you usually minify vendor scripts with the code of your application to minimize load latency, and distribute the resulting code as a binary package. (This is actually what buildbot www is doing)

Like for Python project, I volunteer to manage the switch.
