### ISSUE TITLE
autobahn object undefined after loading AutobahnJS on some websites?

### ISSUE THREAD

**Issue by nhouse** [tavendo/AutobahnJS#135]
I am working on a shopping bookmarklet and Chrome extension and am trying to use AutobahnJS on various retail websites. The plugin is injected into the source of the web page along with other JavaScript.

The `autobahn` object is not defined after injecting AutoBahnJS on many websites. For example:

http://www.walmart.com/ip/Canon-PIXMA-MG2520-Inkjet-All-in-One-Printer/28773460

If you try injecting the code using one of the following methods, no errors are shown in the console, but the `autobahn` object is not defined if you try using it:

Method 1:

    $('body').append('<script scrc="https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.js"></script>');

Method 2:

    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.js";
    script.charset="utf-8";
    document.body.appendChild(script);

However, about half the sites I have tried using AutobahnJS on have worked. Example: http://www.amazon.com/gp/product/B004N49FVO

In my extension I'm not hotlinking -- I have the AutobahnJS plugin code in a single JS file that has other stuff in it as well (such as jQuery).

Do you have any idea why AutobahnJS works on some websites, but not others?

**Comment by davidwdan** [comment]
Nate,

This probably isn't an Autobahn.js related issue.

Instead of injecting Autobahn.js into each page, you would probably want a single local copy that's included with the extension that runs as a background script.  You would then use Chrome's [messaging](https://developer.chrome.com/extensions/messaging) to communicate with the front end script.

If you inject it into each page, a new connection will be established when you navigate to a new page, which is probably not what you want.

**Comment by oberstet** [comment]
@nhouse I'd second David's advice
