### ISSUE TITLE
Undocumented autobahn.Connection.onclose "unsupported" reason

### ISSUE THREAD

**Issue by rafzi** [tavendo/AutobahnJS#161]
The reason "unsupported" does not appear in the doc.

I encountered it when trying to open a non-TLS connection on a TLS site.

Firefox seems to just block the connection, but Chrome gives a nice error message:
>Mixed Content: The page at 'xxx' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'yyy'. This request has been blocked; this endpoint must be available over WSS.

**Comment by oberstet** [comment]
The WHATWG defined WS API in browser does **deliberately** not define specific errors for network related issues like opening an insecure WS connection from a secure HTML page (which is explicitly forbidden by the WS RFC6455 spec).

The reasoning is: rogue JS scripts could otherwise probe around within internal networks.

FWIW, the FF behavior is hence closer to the intentions of the specs ..

We probably should talk a little about these aspects in the AB JS docs, since not everybody will have read the specs ..

**Comment by goeddea** [comment]
I've added mention of both secure WebSocket connections and the 'unsupported' close code to the documentation.

**Comment by erichonkanen** [comment]
I just ran into this and I'm not sure what is causing it?
